title: octiipi.dev
email: octiipi@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  one day all the octiipi will fly
logo: static/favicon.ico
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  octiipi

# Build settings
theme: minima
plugins:
  - jekyll-feed

